explore_node:
  ros__parameters:
    robot_base_frame: base_link
    costmap_topic: /global_costmap/costmap
    visualize: True
    planner_frequency: 0.2
    progress_timeout: 30
    potential_scale: 5.0
    orientation_scale: 0.5
    gain_scale: 1.0
    transform_tolerance: 0.1
    min_frontier_size: 0.4