scan_filter_chain:
  - name: range_filter
    type: laser_filters/RangeFilter
    params:
      lower_limit: 0.2
      upper_limit: 10.0
  - name: sliding_window_filter
    type: laser_filters/SliderWindowFilter
    params:
      window_size: 10