<?xml version="1.0" encoding="utf-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="leo_rover">

    <xacro:property name="wheel_separation" value="0.359" />
    <xacro:property name="wheelbase" value="0.296" />
    <xacro:property name="wheel_diameter" value="0.130" />
    <xacro:property name="wheel_thickness" value="0.066" />

    <!-- LINKS -->
    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://hardware_package/meshes/Chassis.dae" scale="1 1 1" />
            </geometry>
        </visual>
        <inertial>
            <mass value="1.584994"/>
            <origin xyz="-0.019662 0.011643 -0.031802"/>
            <inertia
                ixx="0.01042" ixy="0.001177" ixz="-0.0008871"
                iyy="0.01045" iyz="0.0002226"
                izz="0.01817"/>
        </inertial>
        <collision>
            <geometry>
                <mesh filename="package://hardware_package/meshes/Chassis_outline.stl" />
            </geometry>
        </collision>
        
    </link>

    <link name="wheel_FR_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </visual>
        <material name="black">
            <color rgba="0 0 0 1" />
        </material>

        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </collision>

        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertial>
          <mass value="0.283642"/>
          <origin xyz="0 0.030026 0"/>
          <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
        </inertial>
    </link>

    <link name="wheel_FL_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </visual>
        <material name="black">
            <color rgba="0 0 0 1" />
        </material>
        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </collision>

        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertial>
          <mass value="0.283642"/>
          <origin xyz="0 0.030026 0"/>
          <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
        </inertial>
    </link>

    <link name="wheel_RR_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </visual>
        <material name="black">
            <color rgba="0 0 0 1" />
        </material>

        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </collision>

        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertial>
          <mass value="0.283642"/>
          <origin xyz="0 0.030026 0"/>
          <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
        </inertial>
    </link>

    <link name="wheel_RL_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </visual>
        <material name="black">
            <color rgba="0 0 0 1" />
        </material>
            

        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </collision>

        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertial>
          <mass value="0.283642"/>
          <origin xyz="0 0.030026 0"/>
          <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
        </inertial>
    </link>

    <link name="lidar_link">
        <visual>
            <geometry>
                <mesh filename="package://hardware_package/meshes/Generic_100mm_lidar.stl" scale="1 1 1"/> 
            </geometry>
            <material name="red">
                   <color rgba="1 0 0 1" />
            </material>
            <origin xyz="0 0 0" rpy="0 0 0 " />
        </visual>
    </link>

    <link name="sled_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://hardware_package/meshes/Rover_mounts_v1.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1.0"/>
            </material>
        </visual>
    </link>

    <link name="depth_camera_link">
        <visual name="">
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.090 0.025 0.025"/>
            </geometry>
            <material name="cyan">
                <color rgba="0 1 1 1.0"/>
            </material>
        </visual>
    </link>


    <!-- JOINTS -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>

        <origin xyz="0 0 0" rpy="0 0 0" />        
    </joint>

    <joint name="base_FR_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_FR_link"/>

        <origin xyz="${wheelbase/2} -${wheel_separation/2} -0.1" rpy="-1.5707 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_FL_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_FL_link"/>

        <origin xyz="${wheelbase/2} ${wheel_separation/2} -0.1" rpy="-1.5707 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_RR_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_RR_link"/>

        <origin xyz="-${wheelbase/2} -${wheel_separation/2} -0.1" rpy="-1.5707 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_RL_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_RL_link"/>

        <origin xyz="-${wheelbase/2} ${wheel_separation/2} -0.1" rpy="-1.5707 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="lidar_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>

        <origin xyz="0.02 0.001 0.05" rpy="0 0 0" />
    </joint>

    <joint name="sled_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="sled_link"/>
        
        <origin xyz="0 0 -0.02" rpy="0 0 1.57" />
    </joint>

    <joint name="depth_camera_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="depth_camera_link"/>

        <origin xyz="0.155 0 0" rpy="-1.57 0 -1.57" />
    </joint>
</robot>
