<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="leo_sim">
    <xacro:property name="wheel_separation" value="0.359" />
    <xacro:property name="wheelbase" value="0.296" />
    <xacro:property name="wheel_diameter" value="0.130" />
    <xacro:property name="wheel_thickness" value="0.066" />
    <xacro:property name="pi" value="3.14159" />

    <!-- Materials -->
    <material name="black">
        <color rgba="0 0 0 1" />
    </material>
    <material name="red">
        <color rgba="1 0 0 1" />
    </material>
    <material name="blue">
        <color rgba="0 0 1 1.0"/>
    </material>
    <material name="cyan">
        <color rgba="0 1 1 1.0"/>
    </material>

    <!-- LINKS -->
    <link name="base_footprint" />
    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://leo_description/models/Chassis.dae" scale="1 1 1" />
            </geometry>
        </visual>
        <inertial>
            <mass value="1.584994"/>
            <origin xyz="-0.019662 0.011643 -0.031802"/>
            <inertia
                ixx="0.01042" ixy="0.001177" ixz="-0.0008871"
                iyy="0.01045" iyz="0.0002226"
                izz="0.01817"/>
        </inertial>
        <collision>
            <geometry>
                <mesh filename="package://leo_description/models/Chassis_outline.stl" />
            </geometry>
        </collision>
    </link>
    
    <link name="wheel_FR_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </collision>
        <inertial>
          <mass value="0.283642"/>
          <origin xyz="0 0.030026 0"/>
          <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
        </inertial>
    </link>
    
    <link name="wheel_FL_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </collision>
        <inertial>
          <mass value="0.283642"/>
          <origin xyz="0 0.030026 0"/>
          <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
        </inertial>
    </link>
    
    <link name="wheel_RR_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </collision>
        <inertial>
          <mass value="0.283642"/>
          <origin xyz="0 0.030026 0"/>
          <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
        </inertial>
    </link>
    
    <link name="wheel_RL_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}" />
            </geometry>
        </collision>
        <inertial>
          <mass value="0.283642"/>
          <origin xyz="0 0.030026 0"/>
          <inertia
            ixx="0.000391"  ixy="0.00000123962" ixz="5.52582e-7"
            iyy="0.0004716" iyz="-0.000002082042"
            izz="0.000391"/>
        </inertial>
    </link>
    
    <link name="lidar_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://leo_description/models/Generic_100mm_lidar.stl" scale="1 1 1"/> 
            </geometry>
            <material name="red" />
        </visual>
    </link>
    
    <link name="sled_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://leo_description/models/Rover_mounts_v1.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="blue" />
        </visual>
    </link>
    
    <link name="depth_camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.090 0.025 0.025"/>
            </geometry>
            <material name="cyan" />
        </visual>
    </link>
    
    <!-- JOINTS -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0" />        
    </joint>
    
    <joint name="base_FR_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_FR_link"/>
        <origin xyz="${wheelbase/2} -${wheel_separation/2} -0.1" rpy="1.5707 0 0" />
        <axis xyz="0 0 1" />
    </joint>
    
    <joint name="base_FL_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_FL_link"/>
        <origin xyz="${wheelbase/2} ${wheel_separation/2} -0.1" rpy="1.5707 0 0" />
        <axis xyz="0 0 1" />
    </joint>
    
    <joint name="base_RR_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_RR_link"/>
        <origin xyz="-${wheelbase/2} -${wheel_separation/2} -0.1" rpy="1.5707 0 0" />
        <axis xyz="0 0 1" />
    </joint>
    
    <joint name="base_RL_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_RL_link"/>
        <origin xyz="-${wheelbase/2} ${wheel_separation/2} -0.1" rpy="1.5707 0 0" />
        <axis xyz="0 0 1" />
    </joint>
    
    <joint name="lidar_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.02 0.001 0.05" rpy="0 0 0" />
    </joint>
    
    <joint name="sled_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="sled_link"/>
        <origin xyz="0 0 -0.02" rpy="0 0 1.57" />
    </joint>
    
    <joint name="depth_camera_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="depth_camera_link"/>
        <origin xyz="0.155 0 0" rpy="-1.57 0 -1.57" />
    </joint>

    <!-- Gazebo Plugins -->
    <gazebo>

      <plugin filename="ignition-gazebo-joint-state-publisher-system" name="ignition::gazebo::systems::JointStatePublisher">

        <update_rate>100</update_rate>

        <joint_name>base_FL_joint</joint_name>

        <joint_name>base_FR_joint</joint_name>

        <joint_name>base_RL_joint</joint_name>

        <joint_name>base_RR_joint</joint_name>
        

        <!-- <topic>/world/<world_name>/model/<model_name>/joint_state</topic> THIS IS DEFAULT -->

        <topic>/model/leo_sim/joint_state</topic> <!-- remove world leading prefixes -->

      </plugin>

    </gazebo>

      <!-- Differential Drive -->
  <!-- https://gazebosim.org/api/gazebo/6/classignition_1_1gazebo_1_1systems_1_1DiffDrive.html -->
  <gazebo>
    <plugin filename="ignition-gazebo-diff-drive-system" name="ignition::gazebo::systems::DiffDrive">
      <!-- Wheel Joints -->
      <left_joint>base_FL_joint</left_joint>
      <left_joint>base_RL_joint</left_joint>
      <right_joint>base_FR_joint</right_joint>
      <right_joint>base_RR_joint</right_joint>

      <!-- Kinematics -->
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_diameter/2}</wheel_radius>

      <odom_publish_frequency>0</odom_publish_frequency>
      
      <!-- TF Frames -->
      <frame_id>/odom</frame_id>
      <child_frame_id>/base_footprint</child_frame_id>

      <!-- topics -->
      <!-- <topic>/model/diff_drive_example/cmd_vel</topic> THIS IS DEFAULT -->
      <!-- <odom_topic>/model/diff_drive_example/odometry</odom_topic> THIS IS DEFAULT-->
      <!-- <tf_topic>/model/diff_drive_example/tf</tf_topic> THIS IS DEFAULT -->
      <!-- <tf_topic></tf_topic> Leave blank if you plan to use a filter + imu (e.g. EKF) -->
    </plugin>
  </gazebo>

    <gazebo>
      <plugin
        filename="ignition-gazebo-joint-state-publisher-system"
        name="ignition::gazebo::systems::JointStatePublisher">
        <topic>joint_states</topic>
      </plugin>
    </gazebo>

    <gazebo reference="lidar_link">
        <sensor type="gpu_lidar" name="generic_lidar_sensor">
        <topic>/model/leo_sim/scan</topic>
        <frame_id>lidar_link</frame_id>
        <ignition_frame_id>lidar_link</ignition_frame_id>
        <update_rate>15.0</update_rate>
        <ray>
            <scan>
            <horizontal>
                <samples>270</samples>
                <resolution>1</resolution>
                <min_angle>-${pi*0.75}</min_angle>
                <max_angle>${pi*0.75}</max_angle>
            </horizontal>
            </scan>
            <range>
            <min>0.10</min>
            <max>8.0</max>
            <resolution>0.06</resolution>
            </range>
            <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.02</stddev>
            </noise>
        </ray>
        <always_on>1</always_on>
        <visualize>true</visualize>
        </sensor>
    </gazebo>
    <gazebo>
        <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors">
        <render_engine>ogre2</render_engine>
        </plugin>
  </gazebo>

    <gazebo reference="base_link">
    <sensor name="imu_sensor" type="imu">
      <topic>/model/leo_sim/imu</topic>
      <frame_id>base_link</frame_id>
      <ignition_frame_id>base_link</ignition_frame_id>
      <plugin filename="libignition-gazebo-imu-system.so" name="ignition::gazebo::systems::Imu">
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
     <imu>
     	<angular_velocity>
     	  <x>
     	    <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

  <!-- FRICTION AND PHYSICS -->
  <gazebo reference="wheel_FL_link">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
  </gazebo>

  <gazebo reference="wheel_FR_link">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
  </gazebo>

  <gazebo reference="wheel_RL_link">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
  </gazebo>

  <gazebo reference="wheel_RR_link">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
  </gazebo>
    
</robot>